
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class employee_details extends javax.swing.JFrame {
    
    Connection cn=null;
    Statement st=null;
    Database db=new Database();
    String result=db.Connectdb();
    PreparedStatement pst=null;
    ResultSet rs=null;
    

    /**
     * Creates new form employee_details
     */
    public employee_details() {
        initComponents();
        fetch();
      auto_id();
     
    }
    public void auto_id()
    {
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
           cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
           String sql="select * from employeedetails";
           pst=cn.prepareStatement(sql);
           rs=pst.executeQuery();  
           
           while(rs.next())
           {
              txtid.setText(String.valueOf(Integer.parseInt(rs.getString("id").toString())+1));   
           }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString());       
        }
    }
    
    public void fetch(){
    try
    {
        String var="";
    Class.forName("com.mysql.jdbc.Driver");
           cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
      String sql="select * from employeedetails";
        pst=cn.prepareStatement(sql);
        rs=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }catch(Exception ex)
    {
        JOptionPane.showMessageDialog(null, ex.toString());
    }
    }
  
 
                  
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        txtpostalcode = new javax.swing.JTextField();
        txtid = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtcontact = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsalary = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtdesignation = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nextbtn = new javax.swing.JButton();
        txtdateofjoining = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtaadhar = new javax.swing.JTextField();
        txtqualification = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(1900, 1000));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText(" Employee ID : ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 135, 131, 25));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(" Employee Name : ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 179, 131, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(" Employee Address : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 223, -1, 25));

        txtaddress.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtaddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaddressActionPerformed(evt);
            }
        });
        txtaddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaddressKeyPressed(evt);
            }
        });
        jPanel1.add(txtaddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 224, 330, 25));

        txtcity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcityKeyPressed(evt);
            }
        });
        jPanel1.add(txtcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 264, 145, 25));

        txtpostalcode.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtpostalcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpostalcodeActionPerformed(evt);
            }
        });
        txtpostalcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpostalcodeKeyPressed(evt);
            }
        });
        jPanel1.add(txtpostalcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 302, 191, 25));

        txtid.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });
        txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtidKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtidKeyReleased(evt);
            }
        });
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 136, 40, 25));

        txtname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnameKeyPressed(evt);
            }
        });
        jPanel1.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 180, 328, 25));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText(" Contact Number : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 345, -1, 25));

        txtcontact.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcontact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcontactActionPerformed(evt);
            }
        });
        txtcontact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcontactKeyPressed(evt);
            }
        });
        jPanel1.add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 346, 191, 25));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText(" Designation : ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 389, 125, 25));

        txtsalary.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsalaryActionPerformed(evt);
            }
        });
        txtsalary.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsalaryKeyPressed(evt);
            }
        });
        jPanel1.add(txtsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 434, 191, 25));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(" Salary : ");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 433, 125, 25));

        txtdesignation.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdesignationActionPerformed(evt);
            }
        });
        txtdesignation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdesignationKeyPressed(evt);
            }
        });
        jPanel1.add(txtdesignation, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 390, 191, 25));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Date Of Joining : ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 477, 125, 25));

        btnnew.setBackground(new java.awt.Color(204, 204, 204));
        btnnew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-add-new-16.png"))); // NOI18N
        btnnew.setText("New");
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });
        jPanel1.add(btnnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 609, 125, -1));

        btnsave.setBackground(new java.awt.Color(204, 204, 204));
        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-save-16.png"))); // NOI18N
        btnsave.setText("Save");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(247, 609, 125, -1));

        btnsearch.setBackground(new java.awt.Color(204, 204, 204));
        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-16.png"))); // NOI18N
        btnsearch.setText("Search");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(419, 135, -1, -1));

        btnupdate.setBackground(new java.awt.Color(204, 204, 204));
        btnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnupdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-available-updates-16.png"))); // NOI18N
        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 609, 125, -1));

        btndelete.setBackground(new java.awt.Color(204, 204, 204));
        btndelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-trash-16.png"))); // NOI18N
        btndelete.setText("Delete");
        btndelete.setPreferredSize(new java.awt.Dimension(100, 20));
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btndelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 609, 125, 25));

        btnexit.setBackground(new java.awt.Color(204, 204, 204));
        btnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-close-window-16.png"))); // NOI18N
        btnexit.setText("Exit");
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 609, 125, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Aadhar No.:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 521, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText(" Qualification : ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));

        nextbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        nextbtn.setText(" Next >>");
        nextbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextbtnActionPerformed(evt);
            }
        });
        jPanel1.add(nextbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(905, 609, 125, -1));

        txtdateofjoining.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jPanel1.add(txtdateofjoining, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 477, 191, 25));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText(" City : ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 267, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText(" Postal Code : ");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 305, -1, -1));

        txtaadhar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtaadhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaadharActionPerformed(evt);
            }
        });
        txtaadhar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtaadharKeyPressed(evt);
            }
        });
        jPanel1.add(txtaadhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 513, 191, 25));

        txtqualification.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtqualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtqualificationActionPerformed(evt);
            }
        });
        txtqualification.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtqualificationKeyPressed(evt);
            }
        });
        jPanel1.add(txtqualification, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 549, 191, 25));

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText(" Employee Details");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(380, 380, 380)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(714, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -6, 1330, 80));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Address", "contact", "Designation", "Salary", "Date of joining"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(25);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(25);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(25);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 770, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void txtaddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaddressActionPerformed

    private void txtcontactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcontactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcontactActionPerformed

    private void txtsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsalaryActionPerformed

    private void txtdesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdesignationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdesignationActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        try
        {
            String delete=db.delete("delete from employeedetails  where id='"+txtid.getText()+"' ");
            JOptionPane.showMessageDialog(null, delete);
            fetch();
        }catch(Exception ex)
        {
           JOptionPane.showMessageDialog(null,ex.toString() );
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date=new SimpleDateFormat("yyy MM dd");
        String date1=date.format(txtdateofjoining.getDate());
        
        try
        {
         String insert = db.Insert("insert into employeedetails(id, name, address, city, postalcode, designation,salary, contact, dateofjoining,aadhar_no,qualification)values('"+txtid.getText()+"','"+txtname.getText().toString()+"','"+txtaddress.getText().toString()+"','"+txtcity.getText().toString()+"','"+txtpostalcode.getText()+"','"+txtdesignation.getText().toString()+"','"+txtsalary.getText().toString()+"','"+txtcontact.getText().toString()+"','"+date1+"','"+txtaadhar.getText()+"','"+txtqualification.getText().toString()+"')");
          JOptionPane.showMessageDialog(null, insert);
          fetch();
        }catch(Exception ex)
        {
         JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void txtpostalcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpostalcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpostalcodeActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        home_page obj=new home_page();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat date=new SimpleDateFormat("yyy MM dd");
        String date1=date.format(txtdateofjoining.getDate());
        try
        {
         String update = db.update("update employeedetails set id='"+txtid.getText()+"',name='"+txtname.getText().toString()+"',address='"+txtaddress.getText().toString()+"',city='"+txtcity.getText().toString()+"',postalcode='"+txtpostalcode.getText()+"',designation='"+txtdesignation.getText().toString()+"',salary='"+txtsalary.getText().toString()+"',contact='"+txtcontact.getText().toString()+"',dateofjoining='"+date1+"',aadhar_no='"+txtaadhar.getText()+"',qualification='"+txtqualification.getText().toString()+"' where id='"+txtid.getText()+"' ");
          JOptionPane.showMessageDialog(null, update);
          fetch();
        }catch(Exception ex)
        {
         JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
    try{
    
        Class.forName("com.mysql.jdbc.Driver");
       cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
    
        String sql="select * from employeedetails where id='"+txtid.getText()+"'|| name='"+txtname.getText().toString()+"' || city='"+txtcity.getText().toString()+"' " ;
        pst=cn.prepareStatement(sql);
        rs=pst.executeQuery();
         while(rs.next())
         {
           txtid.setText(rs.getString("id"));
           txtname.setText(rs.getString("name"));
          txtaddress.setText(rs.getString("address"));
          txtcity.setText(rs.getString("city"));
          txtpostalcode.setText(rs.getString("postalcode"));
             txtdesignation.setText(rs.getString("designation"));
          txtsalary.setText(rs.getString("salary"));
           txtcontact.setText(rs.getString("contact"));
          txtdesignation.setText(rs.getString("designation"));
          txtdateofjoining.setDate(rs.getDate("dateofjoining"));
          txtaadhar.setText(rs.getString("aadhar_no"));
          txtqualification.setText(rs.getString("qualification"));
           }
             }   
         catch(Exception ex)
                {
                  JOptionPane.showMessageDialog(null, ex.toString());
                }

    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
        txtid.setText("");
        txtname.setText("");
          txtaddress.setText("");
          txtcity.setText("");
          txtpostalcode.setText("");
          txtdesignation.setText("");
          txtsalary.setText("");
           txtcontact.setText("");
          txtdateofjoining.setDate(null);
        txtaadhar.setText("");
        txtqualification.setText("");
    }//GEN-LAST:event_btnnewActionPerformed

    private void txtidKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {

txtid.setEditable(true);

}
 else
 {
txtid.setEditable(false);

}
    }//GEN-LAST:event_txtidKeyPressed

    private void txtcontactKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcontactKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' && txtcontact.getText().length()<10 || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {

txtcontact.setEditable(true);

}
 else
 {
txtcontact.setEditable(false);

}

    }//GEN-LAST:event_txtcontactKeyPressed

    private void txtnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyPressed
        // TODO add your handling code here:
         if (Character.isAlphabetic(evt.getKeyChar())  || evt.getKeyCode()==46 || evt.getKeyCode()==32 || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {
        txtname.setEditable(true);
        
    }
 else 
{
        txtname.setEditable(false);
       
    }
    }//GEN-LAST:event_txtnameKeyPressed

    private void txtaddressKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaddressKeyPressed
        // TODO add your handling code here:
         if (Character.isAlphabetic(evt.getKeyChar())  || evt.getKeyCode()==46 || evt.getKeyCode()==32 || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {
        txtaddress.setEditable(true);
        
    }
 else 
{
        txtaddress.setEditable(false);
       
    }
    }//GEN-LAST:event_txtaddressKeyPressed

    private void txtcityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcityKeyPressed
        // TODO add your handling code here:
         if (Character.isAlphabetic(evt.getKeyChar())  || evt.getKeyCode()==46 || evt.getKeyCode()==32 || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {
        txtcity.setEditable(true);
        
    }
 else 
{
        txtcity.setEditable(false);
       
    }
    }//GEN-LAST:event_txtcityKeyPressed

    private void txtdesignationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdesignationKeyPressed
        // TODO add your handling code here:
         if (Character.isAlphabetic(evt.getKeyChar())  || evt.getKeyCode()==46 || evt.getKeyCode()==32 || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {
        txtdesignation.setEditable(true);
        
    }
 else 
{
        txtdesignation.setEditable(false);
       
    }
    }//GEN-LAST:event_txtdesignationKeyPressed

    private void txtpostalcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpostalcodeKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {

txtpostalcode.setEditable(true);

}
 else
 {
txtpostalcode.setEditable(false);

}

    }//GEN-LAST:event_txtpostalcodeKeyPressed

    private void txtsalaryKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsalaryKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode()==46 )
 {

txtsalary.setEditable(true);

}
 else
 {
txtsalary.setEditable(false);

}

    }//GEN-LAST:event_txtsalaryKeyPressed

    private void nextbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextbtnActionPerformed
        // TODO add your handling code here:
        employee_payment obj=new employee_payment();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_nextbtnActionPerformed

    private void txtaadharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaadharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaadharActionPerformed

    private void txtqualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtqualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtqualificationActionPerformed

    private void txtaadharKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaadharKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' && txtaadhar.getText().length()<12 || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {

txtaadhar.setEditable(true);

}
 else
 {
txtaadhar.setEditable(false);

}
    }//GEN-LAST:event_txtaadharKeyPressed

    private void txtqualificationKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtqualificationKeyPressed
        // TODO add your handling code here:
         if (Character.isAlphabetic(evt.getKeyChar())  || evt.getKeyCode()==46 || evt.getKeyCode()==32 || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {
        txtqualification.setEditable(true);
        
    }
 else 
{
        txtqualification.setEditable(false);
       
    }
    }//GEN-LAST:event_txtqualificationKeyPressed

    private void txtidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtidKeyReleased
        // TODO add your handling code here:
    
    }//GEN-LAST:event_txtidKeyReleased
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(employee_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new employee_details().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton nextbtn;
    private javax.swing.JTextField txtaadhar;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcontact;
    private com.toedter.calendar.JDateChooser txtdateofjoining;
    private javax.swing.JTextField txtdesignation;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtpostalcode;
    private javax.swing.JTextField txtqualification;
    private javax.swing.JTextField txtsalary;
    // End of variables declaration//GEN-END:variables
}
