
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class product_details extends javax.swing.JFrame {
    Connection cn=null;
    Statement st=null;
    Database db=new Database();
    String result=db.Connectdb();
    PreparedStatement pst=null;
    ResultSet rs=null;
 
    long stockquantity=0;
    /**
     * Creates new form product_details
     */
    public product_details() {
        initComponents();
        setTime();
       auto_id();
    }
    public void auto_id()
    {
        try
        {
           Class.forName("com.mysql.jdbc.Driver");
           cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
           String sql="select * from saleinformation";
           pst=cn.prepareStatement(sql);
           rs=pst.executeQuery();  
           
           while(rs.next())
           {
              txtinvoiceno.setText(String.valueOf(Integer.parseInt(rs.getString("invocenum").toString())+1));   
           }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex.toString());       
        }
    }
 public void fetch(String var)
    {
        double count=0;
        
         try
        {
          
            Class.forName("com.mysql.jdbc.Driver");
           cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
           String sql="select  productcategory,productname, price, quantity, totalamount from saleinformation1 where invocenum='"+var+"'";
            pst=cn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next())
            {
                count=count+Double.parseDouble(rs.getString("totalamount"));
            }
                    
            txtamount.setText(String.valueOf(count));
            fetch();
            
        }catch(Exception ex)
            
        {
               JOptionPane.showMessageDialog(null, ex.toString());  
        }
        
    }
    
    public void fetch(){
    try
    {
       
       Class.forName("com.mysql.jdbc.Driver");
           cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
           String sql="select  productcategory,productname, price, quantity, totalamount from saleinformation1 where invocenum='"+txtinvoiceno.getText().toString()+"' ";
        pst=cn.prepareStatement(sql);
        rs=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    
    }
    catch(Exception ex){
        JOptionPane.showMessageDialog(null, ex.toString());
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtinvoiceno = new javax.swing.JTextField();
        txtcustomername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtcompanyname = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btntotalamount = new javax.swing.JButton();
        txtproductname = new javax.swing.JTextField();
        txtprice = new javax.swing.JTextField();
        txtquantity = new javax.swing.JTextField();
        combocategory = new javax.swing.JComboBox();
        btnaddtocart = new javax.swing.JButton();
        btnremove = new javax.swing.JButton();
        txttotalamount = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnprint = new javax.swing.JButton();
        txttime = new javax.swing.JTextField();
        txtdate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        combospecification = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtamount = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtdiscount = new javax.swing.JTextField();
        btnnetamount = new javax.swing.JButton();
        txtnetamount = new javax.swing.JTextField();
        btnsave = new javax.swing.JButton();
        btnnext = new javax.swing.JButton();
        btnnew = new javax.swing.JButton();
        btndel = new javax.swing.JButton();
        btnsearch = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        txtgst = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1900, 1000));

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText(" Sale Information ");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0), null, null));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText(" Invoice No.:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText(" Customer Name : ");

        txtinvoiceno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtinvoiceno.setMaximumSize(new java.awt.Dimension(170, 30));
        txtinvoiceno.setMinimumSize(new java.awt.Dimension(170, 30));
        txtinvoiceno.setPreferredSize(new java.awt.Dimension(170, 30));
        txtinvoiceno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinvoicenoActionPerformed(evt);
            }
        });
        txtinvoiceno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtinvoicenoKeyPressed(evt);
            }
        });

        txtcustomername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcustomername.setMaximumSize(new java.awt.Dimension(150, 25));
        txtcustomername.setMinimumSize(new java.awt.Dimension(150, 25));
        txtcustomername.setPreferredSize(new java.awt.Dimension(150, 25));
        txtcustomername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomernameActionPerformed(evt);
            }
        });
        txtcustomername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcustomernameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcustomernameKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("  Company Name : ");

        txtcompanyname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtcompanyname.setMaximumSize(new java.awt.Dimension(150, 25));
        txtcompanyname.setMinimumSize(new java.awt.Dimension(150, 25));
        txtcompanyname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtcompanyname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcompanynameActionPerformed(evt);
            }
        });
        txtcompanyname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcompanynameKeyPressed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Product Details : ");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(" Product Name : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText(" Product Category :");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText(" Price : ml/l ");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText(" Quantity : ml/l");

        btntotalamount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btntotalamount.setText(" Total Amount :");
        btntotalamount.setActionCommand(" Amount :");
        btntotalamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntotalamountActionPerformed(evt);
            }
        });

        txtproductname.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtproductname.setMaximumSize(new java.awt.Dimension(150, 25));
        txtproductname.setMinimumSize(new java.awt.Dimension(150, 25));
        txtproductname.setPreferredSize(new java.awt.Dimension(150, 25));
        txtproductname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtproductnameActionPerformed(evt);
            }
        });
        txtproductname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtproductnameKeyPressed(evt);
            }
        });

        txtprice.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtprice.setMaximumSize(new java.awt.Dimension(150, 25));
        txtprice.setMinimumSize(new java.awt.Dimension(150, 25));
        txtprice.setPreferredSize(new java.awt.Dimension(150, 25));
        txtprice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpriceKeyPressed(evt);
            }
        });

        txtquantity.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtquantity.setMaximumSize(new java.awt.Dimension(150, 25));
        txtquantity.setMinimumSize(new java.awt.Dimension(150, 25));
        txtquantity.setPreferredSize(new java.awt.Dimension(150, 25));
        txtquantity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtquantityKeyPressed(evt);
            }
        });

        combocategory.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combocategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Pineapple", "Choclate", "Mango", "Orange", "Tomato", "Redchilli", "Other" }));
        combocategory.setMaximumSize(new java.awt.Dimension(150, 25));
        combocategory.setMinimumSize(new java.awt.Dimension(150, 25));
        combocategory.setPreferredSize(new java.awt.Dimension(170, 30));

        btnaddtocart.setBackground(new java.awt.Color(0, 153, 204));
        btnaddtocart.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnaddtocart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons8-shopping-cart-26.png"))); // NOI18N
        btnaddtocart.setText("Add To Cart ");
        btnaddtocart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddtocartActionPerformed(evt);
            }
        });

        btnremove.setBackground(new java.awt.Color(0, 153, 204));
        btnremove.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnremove.setText(" Remove ");
        btnremove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoveActionPerformed(evt);
            }
        });

        txttotalamount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txttotalamount.setMaximumSize(new java.awt.Dimension(150, 25));
        txttotalamount.setMinimumSize(new java.awt.Dimension(150, 25));
        txttotalamount.setPreferredSize(new java.awt.Dimension(150, 25));
        txttotalamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalamountActionPerformed(evt);
            }
        });
        txttotalamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txttotalamountKeyPressed(evt);
            }
        });

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No.", "Name", "Category", "Price", "Quantity", "Amount"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getColumn(0).setMinWidth(30);
        jTable1.getColumnModel().getColumn(0).setPreferredWidth(30);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(30);

        btnprint.setBackground(new java.awt.Color(0, 204, 255));
        btnprint.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnprint.setText("Print");
        btnprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnprintActionPerformed(evt);
            }
        });

        txttime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });

        txtdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdateActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText(" Date : ");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Time : ");

        combospecification.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combospecification.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Packet", "Bottle", "Can", "other" }));
        combospecification.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                combospecificationMouseReleased(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText(" Product Specification : ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel15)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combocategory, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(combospecification, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtproductname, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btntotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(txttotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnaddtocart, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnremove)
                                .addGap(18, 18, 18)
                                .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {combocategory, combospecification});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttime, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtproductname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combocategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(combospecification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtprice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtquantity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntotalamount, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnaddtocart, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnremove, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnprint, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {combocategory, combospecification});

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText(" Amount : ");

        txtamount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtamount.setMaximumSize(new java.awt.Dimension(150, 25));
        txtamount.setMinimumSize(new java.awt.Dimension(150, 25));
        txtamount.setPreferredSize(new java.awt.Dimension(170, 30));
        txtamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtamountKeyPressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText(" Discount : ");

        txtdiscount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtdiscount.setMaximumSize(new java.awt.Dimension(150, 25));
        txtdiscount.setMinimumSize(new java.awt.Dimension(150, 25));
        txtdiscount.setPreferredSize(new java.awt.Dimension(170, 30));
        txtdiscount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdiscountKeyPressed(evt);
            }
        });

        btnnetamount.setBackground(new java.awt.Color(204, 204, 204));
        btnnetamount.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnetamount.setText(" Net Amount : ");
        btnnetamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnetamountActionPerformed(evt);
            }
        });

        txtnetamount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnetamount.setMaximumSize(new java.awt.Dimension(150, 25));
        txtnetamount.setMinimumSize(new java.awt.Dimension(150, 25));
        txtnetamount.setPreferredSize(new java.awt.Dimension(170, 30));
        txtnetamount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnetamountActionPerformed(evt);
            }
        });
        txtnetamount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnetamountKeyPressed(evt);
            }
        });

        btnsave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-save-16.png"))); // NOI18N
        btnsave.setText(" Save ");
        btnsave.setMaximumSize(new java.awt.Dimension(100, 30));
        btnsave.setMinimumSize(new java.awt.Dimension(100, 30));
        btnsave.setPreferredSize(new java.awt.Dimension(100, 30));
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnnext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnext.setText("Next >>");
        btnnext.setMaximumSize(new java.awt.Dimension(100, 30));
        btnnext.setMinimumSize(new java.awt.Dimension(100, 30));
        btnnext.setPreferredSize(new java.awt.Dimension(100, 30));
        btnnext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnextActionPerformed(evt);
            }
        });

        btnnew.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnnew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-add-new-16.png"))); // NOI18N
        btnnew.setText(" New ");
        btnnew.setMaximumSize(new java.awt.Dimension(100, 30));
        btnnew.setMinimumSize(new java.awt.Dimension(100, 30));
        btnnew.setPreferredSize(new java.awt.Dimension(100, 30));
        btnnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnewActionPerformed(evt);
            }
        });

        btndel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btndel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-trash-16.png"))); // NOI18N
        btndel.setText(" Delete ");
        btndel.setMaximumSize(new java.awt.Dimension(100, 30));
        btndel.setMinimumSize(new java.awt.Dimension(100, 30));
        btndel.setPreferredSize(new java.awt.Dimension(100, 30));
        btndel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndelActionPerformed(evt);
            }
        });

        btnsearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/icons8-search-16.png"))); // NOI18N
        btnsearch.setText(" Search ");
        btnsearch.setMaximumSize(new java.awt.Dimension(100, 30));
        btnsearch.setMinimumSize(new java.awt.Dimension(100, 30));
        btnsearch.setPreferredSize(new java.awt.Dimension(100, 30));
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });

        btnexit.setBackground(new java.awt.Color(204, 204, 204));
        btnexit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons8-close-window-16.png")); // NOI18N
        btnexit.setText("Exit");
        btnexit.setMaximumSize(new java.awt.Dimension(100, 30));
        btnexit.setMinimumSize(new java.awt.Dimension(100, 30));
        btnexit.setPreferredSize(new java.awt.Dimension(100, 30));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText(" GST: ");

        txtgst.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtgst.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtgstKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(224, 224, 224)
                                        .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(31, 31, 31))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(btnnetamount)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtnetamount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(144, 144, 144)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(93, 93, 93)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtgst, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(49, 49, 49)
                                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(550, 550, 550)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(260, 260, 260)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(68, 68, 68))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtcustomername, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtinvoiceno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(834, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtinvoiceno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcompanyname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcustomername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtamount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnnetamount, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnetamount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtgst, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnnew, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnnext, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btndel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnexit, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcompanynameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcompanynameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcompanynameActionPerformed

    private void btntotalamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntotalamountActionPerformed
        // TODO add your handling code here:
        double total;
        double price=Integer.parseInt(txtprice.getText().toString());
        double quantity=Integer.parseInt(txtquantity.getText().toString());
        total=price*quantity;
        txttotalamount.setText(String.valueOf(total));
    }//GEN-LAST:event_btntotalamountActionPerformed

    private void txtproductnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtproductnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtproductnameActionPerformed

    private void btnremoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoveActionPerformed
        // TODO add your handling code here:
        try
        {
            
            
           Class.forName("com.mysql.jdbc.Driver");
           cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
           String sql="select * from stock where name = '"+txtproductname.getText().toString()+"' && category='"+combocategory.getSelectedItem().toString()+"' && specification='"+combospecification.getSelectedItem().toString()+"' ";
           pst=cn.prepareStatement(sql);
           rs=pst.executeQuery();  
           
           while(rs.next())
           {
               stockquantity =  Long.parseLong(rs.getString("quantity"));
           } 
           stockquantity = stockquantity + Long.parseLong(txtquantity.getText()); 
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
        
        try
        {
            String var=txtinvoiceno.getText().toString();
            String delete=db.delete("delete from saleinformation1 where productname = '"+txtproductname.getText().toString()+"' && productcategory='"+combocategory.getSelectedItem().toString()+"' && productspecification='"+combospecification.getSelectedItem().toString()+"' ");
            JOptionPane.showMessageDialog(null, delete);
            String update=db.update("update stock set quantity='"+stockquantity+"' where name = '"+txtproductname.getText().toString()+"' && category='"+combocategory.getSelectedItem().toString()+"' && specification='"+combospecification.getSelectedItem().toString()+"' ");
            fetch();
            fetch(var);
        }catch(Exception ex)
        {
           JOptionPane.showMessageDialog(null,ex.toString() );
        }
    }//GEN-LAST:event_btnremoveActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
      try{
         String insert=db.Insert("insert into saleinformation(invocenum, customername, companyname, date, time, productname, productcategory,productspecification, price, quantity, totalamount, amount, netamount, discount, gst)values('"+txtinvoiceno.getText()+"','"+txtcustomername.getText().toString()+"','"+txtcompanyname.getText().toString()+"','"+txtdate.getText().toString()+"','"+txttime.getText().toString()+"','"+txtproductname.getText().toString()+"','"+combocategory.getSelectedItem().toString()+"','"+combospecification.getSelectedItem().toString()+"','"+txtprice.getText().toString()+"','"+txtquantity.getText()+"','"+txttotalamount.getText().toString()+"','"+txtamount.getText().toString()+"','"+txtnetamount.getText().toString()+"','"+txtdiscount.getText().toString()+"','"+txtgst.getText().toString()+"')");
        
        JOptionPane.showMessageDialog(null, insert);
        fetch();
        }catch(Exception ex)
        {
        
           JOptionPane.showMessageDialog(null, ex.toString());
        }
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        // TODO add your handling code here:
        home_page obj=new home_page();
        obj.setVisible(true);
        this.hide();
        
    }//GEN-LAST:event_btnexitActionPerformed

    private void txtinvoicenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinvoicenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtinvoicenoActionPerformed

    private void txttotalamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttotalamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttotalamountActionPerformed

    private void btndelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndelActionPerformed
        // TODO add your handling code here:
        try
        {
            String delete=db.delete("delete from saleinformation where invocenum='"+txtinvoiceno.getText()+"' ");
            JOptionPane.showMessageDialog(null, delete);
            fetch();
        }catch(Exception ex)
        {
           JOptionPane.showMessageDialog(null,ex.toString() );
        }
    }//GEN-LAST:event_btndelActionPerformed

    private void txtcustomernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcustomernameActionPerformed

    private void btnnextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnextActionPerformed
        // TODO add your handling code here
        payment_details obj=new payment_details();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_btnnextActionPerformed

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimeActionPerformed

    private void txtdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdateActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtdateActionPerformed

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        try{
            Class.forName("com.mysql.jdbc.Driver");
       cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
    
        String sql="select * from saleinformation  where invocenum='"+txtinvoiceno.getText()+"'|| companyname='"+txtcompanyname.getText().toString()+"'" ;
        pst=cn.prepareStatement(sql);
        rs=pst.executeQuery();
        
        while(rs.next())
        {
            txtinvoiceno.setText(rs.getString("invocenum"));
         txtcustomername.setText(rs.getString("customername"));
         txtcompanyname.setText(rs.getString("companyname"));
          txtdate.setText(rs.getString("date"));
         txttime.setText(rs.getString("time"));
         txtproductname.setText(rs.getString("productname"));
         combocategory.setSelectedItem(rs.getString("productcategory")); 
         combospecification.setSelectedItem(rs.getString("productspecification"));
         txtprice.setText(rs.getString("price"));
         txtquantity.setText(rs.getString("quantity"));
         txttotalamount.setText(rs.getString("totalamount"));
         txtamount.setText(rs.getString("amount"));
         txtnetamount.setText(rs.getString("netamount"));
         txtdiscount.setText(rs.getString("discount"));
         txtgst.setText(rs.getString("gst"));
         
        }
        fetch();
        }catch(Exception ex)
        {
          JOptionPane.showMessageDialog(null,ex.toString()); 
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void btnnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnewActionPerformed
        // TODO add your handling code here:
          txtinvoiceno.setText("");
         txtcustomername.setText("");
         txtcompanyname.setText("");
         txtdate.setText("");
         txttime.setText("");
         txtproductname.setText("");
         combocategory.setSelectedItem(""); 
         combospecification.setSelectedItem("");
         txtprice.setText("");
         txtquantity.setText("");
         txttotalamount.setText("");
         txtamount.setText("");
         txtnetamount.setText("");
         txtdiscount.setText("");
         txtgst.setText("");
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
    }//GEN-LAST:event_btnnewActionPerformed

    private void btnnetamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnetamountActionPerformed
        // TODO add your handling code here:
        double net_amount;
        
        double amount = Double.parseDouble(txtamount.getText().toString());
        double discount = (Double.parseDouble(txtdiscount.getText().toString()) * amount )/100 ;
        double gst = (Double.parseDouble(txtgst.getText().toString()) * amount)/100;
        double netamount = amount-discount+gst;
        txtnetamount.setText(String.valueOf(netamount));
        
    }//GEN-LAST:event_btnnetamountActionPerformed

    private void txtinvoicenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinvoicenoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {

txtinvoiceno.setEditable(true);

}
 else
 {
txtinvoiceno.setEditable(false);

}
    }//GEN-LAST:event_txtinvoicenoKeyPressed

    private void txtcustomernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustomernameKeyPressed
        // TODO add your handling code here:
         if (Character.isAlphabetic(evt.getKeyChar())  || evt.getKeyCode()==46 || evt.getKeyCode()==32 || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {
        txtcustomername.setEditable(true);
        
    }
 else 
{
        txtcustomername.setEditable(false);
       
    }
    }//GEN-LAST:event_txtcustomernameKeyPressed

    private void txtcompanynameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcompanynameKeyPressed
        // TODO add your handling code here:
         if (Character.isAlphabetic(evt.getKeyChar())  || evt.getKeyCode()==46 || evt.getKeyCode()==32 || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {
        txtcompanyname.setEditable(true);
        
    }
 else 
{
        txtcompanyname.setEditable(false);
       
    }
    }//GEN-LAST:event_txtcompanynameKeyPressed

    private void txtproductnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproductnameKeyPressed
        // TODO add your handling code here:
         if (Character.isAlphabetic(evt.getKeyChar())  || evt.getKeyCode()==46 || evt.getKeyCode()==32 || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {
        txtproductname.setEditable(true);
        
    }
 else 
{
        txtproductname.setEditable(false);
       
    }
    }//GEN-LAST:event_txtproductnameKeyPressed

    private void txtquantityKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtquantityKeyPressed
        // TODO add your handling code here:
        
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {

txtquantity.setEditable(true);

}
 else
 {
txtquantity.setEditable(false);

}
    }//GEN-LAST:event_txtquantityKeyPressed

    private void txtpriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpriceKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode()==46 )
 {

txtprice.setEditable(true);

}
 else
 {
txtprice.setEditable(false);

}

    }//GEN-LAST:event_txtpriceKeyPressed

    private void txttotalamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttotalamountKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode()==46 )
 {

txttotalamount.setEditable(true);

}
 else
 {
txttotalamount.setEditable(false);

}

    }//GEN-LAST:event_txttotalamountKeyPressed

    private void txtamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtamountKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode()==46 )
 {

txtamount.setEditable(true);

}
 else
 {
txtamount.setEditable(false);

}

    }//GEN-LAST:event_txtamountKeyPressed

    private void txtdiscountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdiscountKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode()==46 )
 {

txtdiscount.setEditable(true);

}
 else
 {
txtdiscount.setEditable(false);

}

    }//GEN-LAST:event_txtdiscountKeyPressed

    private void txtnetamountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnetamountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnetamountActionPerformed

    private void txtnetamountKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnetamountKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode()==46 )
 {

txtnetamount.setEditable(true);

}
 else
 {
txtnetamount.setEditable(false);

}

    }//GEN-LAST:event_txtnetamountKeyPressed

    private void txtgstKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtgstKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode()==46 )
 {

txtgst.setEditable(true);

}
 else
 {
txtgst.setEditable(false);

}

    }//GEN-LAST:event_txtgstKeyPressed

    private void btnaddtocartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddtocartActionPerformed
        // TODO add your handling code here:
        try
        {
            
            
           Class.forName("com.mysql.jdbc.Driver");
           cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
           String sql="select * from stock where name = '"+txtproductname.getText().toString()+"' && category='"+combocategory.getSelectedItem().toString()+"' && specification='"+combospecification.getSelectedItem().toString()+"' ";
           pst=cn.prepareStatement(sql);
           rs=pst.executeQuery();  
           
           while(rs.next())
           {
               stockquantity =  Long.parseLong(rs.getString("quantity"));
           } 
           
           if(stockquantity>=Long.parseLong(txtquantity.getText()))
           {
           
                stockquantity = stockquantity - Long.parseLong(txtquantity.getText()); 
                String var=txtinvoiceno.getText().toString();
                String insert=db.Insert("insert into saleinformation1(invocenum, customername, companyname, date, time, productname, productcategory,productspecification, price, quantity, totalamount)values('"+var+"','"+txtcustomername.getText().toString()+"','"+txtcompanyname.getText().toString()+"','"+txtdate.getText().toString()+"','"+txttime.getText().toString()+"','"+txtproductname.getText().toString()+"','"+combocategory.getSelectedItem().toString()+"','"+combospecification.getSelectedItem().toString()+"','"+txtprice.getText().toString()+"','"+txtquantity.getText().toString()+"','"+txttotalamount.getText().toString()+"')");    
                String update=db.update("update stock set quantity='"+stockquantity+"' where name = '"+txtproductname.getText().toString()+"' && category='"+combocategory.getSelectedItem().toString()+"' && specification='"+combospecification.getSelectedItem().toString()+"' ");
                JOptionPane.showMessageDialog(null, insert);  
                fetch(var);
           }
           else
           {
               JOptionPane.showMessageDialog(null, "Product not available in stock");
           }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
        
        
    }//GEN-LAST:event_btnaddtocartActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row = jTable1.getSelectedRow();  
        
        txtproductname.setText(jTable1.getValueAt(row, 0).toString());
        combocategory.setSelectedItem(jTable1.getValueAt(row, 1).toString());
        combospecification.setSelectedItem(jTable1.getValueAt(row, 2).toString());
        txtprice.setText(jTable1.getValueAt(row, 3).toString());
        txtquantity.setText(jTable1.getValueAt(row, 4).toString());
        txttotalamount.setText(jTable1.getValueAt(row, 5).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void txtcustomernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcustomernameKeyReleased
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
       cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
    
        String sql="select * from registration where name ='"+txtcustomername.getText()+"' " ;
        pst=cn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next())
        {
           txtcustomername.setText(rs.getString("name"));
           txtcompanyname.setText(rs.getString("address"));

          }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
       
    }//GEN-LAST:event_txtcustomernameKeyReleased

    private void combospecificationMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_combospecificationMouseReleased
         // TODO add your handling code here:
        
         try
        {
            
        Class.forName("com.mysql.jdbc.Driver");
        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
        String sql="select * from productinformation where name ='"+txtproductname.getText()+"' && category = '"+combocategory.getSelectedItem()+"' && specification = '"+combospecification.getSelectedItem()+"'" ;
        pst=cn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next())
        {
           txtprice.setText(rs.getString("price"));  
        }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
         
         
    }//GEN-LAST:event_combospecificationMouseReleased

    private void btnprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnprintActionPerformed
        // TODO add your handling code here:
         Connection cn=null;
        try
           {
            
              String id = txtinvoiceno.getText(); 
               
           Class.forName("com.mysql.jdbc.Driver");
           System.out.println("Driver Registered");
        cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");           
            System.out.println("Connection Success");
           String path="C:\\Users\\Admin\\Documents\\NetBeansProjects\\manufacturing_fruit_product_management_system\\src\\Report1\\Sale_bill_format.jrxml";
            Map parameters = new HashMap();
           
           parameters.put("id",id);
           
           
           JasperDesign design = JRXmlLoader.load(path);
    //JasperReport report = JasperCompileManager.compileReport(design);
           JasperReport jr=JasperCompileManager.compileReport(design);
           
           JasperPrint jp=JasperFillManager.fillReport(jr, parameters, cn);
           JasperViewer jv=new JasperViewer(jp);
           jv.setVisible(true);
          // jv.setVisible(true);
           }catch(Exception ex)
           {
           System.out.println(ex);
           }

    }//GEN-LAST:event_btnprintActionPerformed

    public void setTime()
    {
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(product_details.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                Date date=new Date();
                SimpleDateFormat tf=new SimpleDateFormat("h:mm:ss aa");
                SimpleDateFormat df=new SimpleDateFormat("yyy MM dd");
                String time=tf.format(date);
                txttime.setText(time.split(" ")[0]+(" ")+time.split(" ")[1]);
                txtdate.setText(df.format(date));
            }
        }).start();
    }/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_details().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddtocart;
    private javax.swing.JButton btndel;
    private javax.swing.JButton btnexit;
    private javax.swing.JButton btnnetamount;
    private javax.swing.JButton btnnew;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprint;
    private javax.swing.JButton btnremove;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnsearch;
    private javax.swing.JButton btntotalamount;
    private javax.swing.JComboBox combocategory;
    private javax.swing.JComboBox combospecification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtamount;
    private javax.swing.JTextField txtcompanyname;
    private javax.swing.JTextField txtcustomername;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtdiscount;
    private javax.swing.JTextField txtgst;
    private javax.swing.JTextField txtinvoiceno;
    private javax.swing.JTextField txtnetamount;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtproductname;
    private javax.swing.JTextField txtquantity;
    private javax.swing.JTextField txttime;
    private javax.swing.JTextField txttotalamount;
    // End of variables declaration//GEN-END:variables
}
