
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class purchase_payment extends javax.swing.JFrame {
    Connection cn=null;
    Statement st=null;
    Database db=new Database();
    String result=db.Connectdb();
    PreparedStatement pst=null;
    ResultSet rs=null;
 

    /**
     * Creates new form purchase_payment
     */
    public purchase_payment() {
        initComponents();
        setTime();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        txttime = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        remainamtbtn = new javax.swing.JButton();
        txtinvoiceno = new javax.swing.JTextField();
        txtsuppliername = new javax.swing.JTextField();
        txtnetamt = new javax.swing.JTextField();
        combomodeofpay = new javax.swing.JComboBox();
        txtpaidamt = new javax.swing.JTextField();
        txtremainamt = new javax.swing.JTextField();
        combostatus = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        savebtn = new javax.swing.JButton();
        backbtn = new javax.swing.JButton();
        exitbtn = new javax.swing.JButton();
        searchbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1900, 1000));

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("Supplier Payment Details");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(" Date : ");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText(" Time : ");

        txtdate.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txttime.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtdate, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(txttime))
                .addContainerGap(924, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txttime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText(" Invoice No. : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText(" Supplier Name ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Mode Of Payment :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Net Amount : ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Paid Amount : ");

        remainamtbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        remainamtbtn.setText(" Remaining Amount :");
        remainamtbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainamtbtnActionPerformed(evt);
            }
        });

        txtinvoiceno.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtinvoiceno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtinvoicenoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtinvoicenoKeyReleased(evt);
            }
        });

        txtsuppliername.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtsuppliername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtsuppliernameKeyPressed(evt);
            }
        });

        txtnetamt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtnetamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnetamtKeyPressed(evt);
            }
        });

        combomodeofpay.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combomodeofpay.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Credit Card", "Digital Wallet", "Cash" }));

        txtpaidamt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtpaidamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtpaidamtKeyPressed(evt);
            }
        });

        txtremainamt.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtremainamt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtremainamtKeyPressed(evt);
            }
        });

        combostatus.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        combostatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paid", "Unpaid" }));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Payment Status : ");

        savebtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        savebtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons8-save-16.png")); // NOI18N
        savebtn.setText(" Save ");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        backbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        backbtn.setText("<<Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        exitbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        exitbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons8-close-window-16.png")); // NOI18N
        exitbtn.setText("Exit");
        exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitbtnActionPerformed(evt);
            }
        });

        searchbtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        searchbtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\icons8-search-16.png")); // NOI18N
        searchbtn.setText("Search");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(savebtn)
                        .addGap(78, 78, 78)
                        .addComponent(backbtn))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(remainamtbtn))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtsuppliername)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtnetamt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtpaidamt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combomodeofpay, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtremainamt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtinvoiceno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchbtn)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jLabel9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(156, 156, 156)
                                .addComponent(exitbtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(combostatus, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {combomodeofpay, combostatus, txtnetamt, txtpaidamt, txtremainamt, txtsuppliername});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtinvoiceno, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchbtn))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsuppliername, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combomodeofpay, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtnetamt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtpaidamt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(remainamtbtn)
                            .addComponent(txtremainamt, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(combostatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savebtn)
                    .addComponent(backbtn)
                    .addComponent(exitbtn))
                .addGap(0, 374, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {combomodeofpay, combostatus, txtinvoiceno, txtnetamt, txtpaidamt, txtremainamt, txtsuppliername});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttimeActionPerformed

    private void exitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitbtnActionPerformed
        // TODO add your handling code here:
        home_page obj=new home_page();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_exitbtnActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        // TODO add your handling code here:
        purchase_details obj=new purchase_details();
        obj.setVisible(true);
        this.hide();
    }//GEN-LAST:event_backbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        // TODO add your handling code here:
         try{
        String insert=db.Insert("insert into  supplier_paymentdetails(invoiceno,suppliername,modeofpayment,netamount, paidamount, remainingamount,paymentstatus,date,time)values('"+txtinvoiceno.getText()+"','"+txtsuppliername.getText().toString()+"','"+combomodeofpay.getSelectedItem().toString()+"','"+txtnetamt.getText().toString()+"','"+txtpaidamt.getText().toString()+"','"+txtremainamt.getText().toString()+"','"+combostatus.getSelectedItem().toString()+"','"+txtdate.getText().toString()+"','"+txttime.getText().toString()+"')");
          JOptionPane.showMessageDialog(null, insert);     
        }catch(Exception ex)
        {
        JOptionPane.showMessageDialog(null, ex.toString()); 
        }
    }//GEN-LAST:event_savebtnActionPerformed

    private void txtpaidamtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpaidamtKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode()==46 )
 {

txtpaidamt.setEditable(true);

}
 else
 {
txtpaidamt.setEditable(false);

}
    }//GEN-LAST:event_txtpaidamtKeyPressed

    private void txtremainamtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtremainamtKeyPressed
        // TODO add your handling code here:
         if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode()==46 )
 {

txtremainamt.setEditable(true);

}
 else
 {
txtremainamt.setEditable(false);

}
    }//GEN-LAST:event_txtremainamtKeyPressed

    private void remainamtbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainamtbtnActionPerformed
        // TODO add your handling code here:
        double remainingamount;
        double netamount= Double.parseDouble(txtnetamt.getText().toString());
        double paidamount= Double.parseDouble(txtpaidamt.getText().toString());
        remainingamount=netamount-paidamount;
        txtremainamt.setText(String.valueOf(remainingamount));

    }//GEN-LAST:event_remainamtbtnActionPerformed

    private void txtnetamtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnetamtKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE || evt.getKeyCode()==46 )
 {

txtnetamt.setEditable(true);

}
 else
 {
txtnetamt.setEditable(false);

}
    }//GEN-LAST:event_txtnetamtKeyPressed

    private void txtinvoicenoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinvoicenoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyChar() >= '0' && evt.getKeyChar() <= '9' || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {

txtinvoiceno.setEditable(true);

}
 else
 {
txtinvoiceno.setEditable(false);

}
    }//GEN-LAST:event_txtinvoicenoKeyPressed

    private void txtsuppliernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtsuppliernameKeyPressed
        // TODO add your handling code here:
         if (Character.isAlphabetic(evt.getKeyChar())  || evt.getKeyCode()==46 || evt.getKeyCode()==32 || evt.getKeyCode() == evt.VK_BACK_SPACE)
 {
        txtsuppliername.setEditable(true);
        
    }
 else 
{
        txtsuppliername.setEditable(false);
       
    }
    }//GEN-LAST:event_txtsuppliernameKeyPressed

    private void txtinvoicenoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinvoicenoKeyReleased
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
       cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
    
        String sql="select * from purchaseinformation where invocenum='"+txtinvoiceno.getText()+"' " ;
        pst=cn.prepareStatement(sql);
        rs=pst.executeQuery();
        while(rs.next())
        {
         txtinvoiceno.setText(rs.getString("invocenum"));
           txtsuppliername.setText(rs.getString("supplierrname"));
           txtnetamt.setText(rs.getString("netamount"));

          }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null, ex.toString());
        }
       
    }//GEN-LAST:event_txtinvoicenoKeyReleased

      private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
         try
        {
             Class.forName("com.mysql.jdbc.Driver");
       cn=DriverManager.getConnection("jdbc:mysql://localhost:3306/manufacturing_fruit_product_management","root","root");
    
        String sql="select * from supplier_paymentdetails where invoiceno='"+txtinvoiceno.getText()+"' || supplierername='"+txtsuppliername.getText().toString()+"' " ;
        pst=cn.prepareStatement(sql);
        rs=pst.executeQuery();
        
        while(rs.next())
        {
            txtinvoiceno.setText(rs.getString("invoiceno"));
            txtsuppliername.setText(rs.getString("customername"));
           combomodeofpay.setSelectedItem(rs.getString("modeofpayment"));
            txtnetamt.setText(rs.getString("netamount"));
            txtpaidamt.setText(rs.getString("paidamount"));
            txtremainamt.setText(rs.getString("remainingamount"));
            combostatus.setSelectedItem(rs.getString("paymentstatus"));
            txtdate.setText(rs.getString("date"));
            txttime.setText(rs.getString("time"));
        }
        
        }
        catch(Exception ex)
        {
           JOptionPane.showMessageDialog(null,ex.toString()); 
       
    }
    }  
      public void setTime()
    {
        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException ex) {
                    Logger.getLogger(purchase_details.class.getName()).log(Level.SEVERE, null, ex);
                }
                
                Date date=new Date();
                SimpleDateFormat tf=new SimpleDateFormat("h:mm:ss aa");
                SimpleDateFormat df=new SimpleDateFormat("yyy MM dd");
                String time=tf.format(date);
                txttime.setText(time.split(" ")[0]+(" ")+time.split(" ")[1]);
                txtdate.setText(df.format(date));
            }
        }).start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purchase_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purchase_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purchase_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purchase_payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                          java.awt.EventQueue.invokeLater(new Runnable()
                {
                   public void run() {
                new purchase_payment().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JComboBox combomodeofpay;
    private javax.swing.JComboBox combostatus;
    private javax.swing.JButton exitbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton remainamtbtn;
    private javax.swing.JButton savebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtinvoiceno;
    private javax.swing.JTextField txtnetamt;
    private javax.swing.JTextField txtpaidamt;
    private javax.swing.JTextField txtremainamt;
    private javax.swing.JTextField txtsuppliername;
    private javax.swing.JTextField txttime;
    // End of variables declaration//GEN-END:variables
}
